#
# run with "rubocop" from this directory (no arguments)
# configuration documentation https://rubocop-sketchup.readthedocs.io/en/latest/
# this config is similar to https://rubocop-sketchup.readthedocs.io/en/latest/basic_usage/
# needs
# $ gem query --local | grep rubocop
# rubocop (0.93.0)
# rubocop-ast (1.4.1)
# rubocop-sketchup (0.18.0)
#
require: rubocop-sketchup

AllCops:
  DisabledByDefault: true
  Exclude:
  - test/*

SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: true

SketchupRequirements:
  Enabled: true

SketchupSuggestions:
  Enabled: true

SketchupBugs:
  Enabled: true
